#include "Bible/Bible.h"
#include "HellLogging.h"
#include <unordered_map>
#include "Util.h">

namespace Bible {

    void InitWeaponInfo() {
        WeaponInfo& aks74u = CreateWeaponInfo("AKS74U");
        aks74u.itemInfoName = "AKS74U";
        aks74u.modelName = "AKS74U";
        aks74u.type = WeaponType::AUTOMATIC;
        aks74u.damage = 25;
        aks74u.animationNames.idle = "AKS74U_Idle";
        aks74u.animationNames.walk = "AKS74U_Walk";
        aks74u.animationNames.draw = "AKS74U_Draw";
        aks74u.animationNames.reload = "AKS74U_Reload";
        aks74u.animationNames.reloadempty.push_back("AKS74U_ReloadEmpty2");
        aks74u.animationNames.fire.push_back("AKS74U_Fire0");
        aks74u.animationNames.fire.push_back("AKS74U_Fire1");
        aks74u.animationNames.fire.push_back("AKS74U_Fire2");
        aks74u.animationNames.draw = "AKS74U_Draw";
        aks74u.meshMaterials["ArmsMale"] = "Hands";
        aks74u.meshMaterials["ArmsFemale"] = "FemaleArms";
        aks74u.meshMaterials["AKS74UBarrel"] = "AKS74U_4";
        aks74u.meshMaterials["AKS74UBolt"] = "AKS74U_1";
        aks74u.meshMaterials["AKS74UHandGuard"] = "AKS74U_0";
        aks74u.meshMaterials["AKS74UMag"] = "AKS74U_3";
        aks74u.meshMaterials["AKS74UPistolGrip"] = "AKS74U_2";
        aks74u.meshMaterials["AKS74UReceiver"] = "AKS74U_1";
        aks74u.meshMaterials["AKS74U_ScopeSupport"] = "AKS74U_ScopeSupport";
        aks74u.meshMaterials["AKS74U_ScopeMain"] = "AKS74U_ScopeMain";
        aks74u.meshMaterials["AKS74U_ScopeFrontCap"] = "AKS74U_ScopeVxor";
        aks74u.meshMaterials["AKS74U_ScopeBackCap"] = "AKS74U_ScopeVxor";
        aks74u.meshMaterials["AKS74U_RedDot"] = "Gold";
        aks74u.meshMaterials["AKS74U_Lens"] = "Gold";
        aks74u.hiddenMeshAtStart.push_back("AKS74U_ScopeFrontCap");
        aks74u.hiddenMeshAtStart.push_back("AKS74U_ScopeBackCap");
        aks74u.hiddenMeshAtStart.push_back("ArmsFemale");
        aks74u.hiddenMeshAtStart.push_back("AKS74U_Lens");
        aks74u.hiddenMeshAtStart.push_back("AKS74U_RedDot");
        aks74u.ammoInfoName = "AKS74U";
        aks74u.magSize = 30;
        aks74u.muzzleFlashBoneName = "Weapon";
        aks74u.muzzleFlashOffset = glm::vec3(0, 0.002, 0.02f);
        aks74u.casingEjectionBoneName = "SlideCatch";
        aks74u.casingEjectionOffset = glm::vec3(0, 0, 0);
        aks74u.animationCancelFrames.fire = 3.0f;
        aks74u.animationCancelFrames.reload = 80.0f;
        aks74u.animationCancelFrames.reloadFromEmpty = 95.0f;
        aks74u.animationCancelFrames.draw = 75.0f;
        aks74u.animationCancelFrames.adsFire = 18.0f;
        aks74u.audioFiles.fire.push_back("AKS74U_Fire0.wav");
        aks74u.audioFiles.fire.push_back("AKS74U_Fire1.wav");
        aks74u.audioFiles.fire.push_back("AKS74U_Fire2.wav");
        aks74u.audioFiles.fire.push_back("AKS74U_Fire3.wav");
        aks74u.audioFiles.reload = "AKS74U_Reload.wav";
        aks74u.audioFiles.reloadEmpty = "AKS74U_ReloadEmpty.wav";
        aks74u.animationSpeeds.fire = 1.625f;
        aks74u.animationSpeeds.adsFire = 1.625f;
        aks74u.animationSpeeds.draw = 1.225f;
        aks74u.muzzleFlashBoneName = "Muzzle";
        aks74u.casingEjectionBoneName = "EjectionPort";
        aks74u.muzzleFlashScale = 1.5f;
        aks74u.casingEjectionImpulse = 0.0175f;
        aks74u.animationNames.adsIn = "AKS74U_ADS_In";
        aks74u.animationNames.adsOut = "AKS74U_ADS_Out";
        aks74u.animationNames.adsIdle = "AKS74U_ADS_Idle";
        aks74u.animationNames.adsWalk = "AKS74U_ADS_Walk";
        aks74u.animationNames.adsFire.push_back("AKS74U_ADS_Fire0");
        aks74u.animationNames.adsFire.push_back("AKS74U_ADS_Fire1");
        aks74u.animationNames.adsFire.push_back("AKS74U_ADS_Fire2");
        aks74u.reloadMagInFrameNumber = 23;
        aks74u.reloadEmptyMagInFrameNumber = 21;


        WeaponInfo& glock = CreateWeaponInfo("Glock");
        glock.hiddenMeshAtStart.push_back("ArmsFemale");
        glock.hiddenMeshAtStart.push_back("LeupoldRedDot");
        glock.hiddenMeshAtStart.push_back("LeupoldRedDotGlass");
        glock.hiddenMeshAtStart.push_back("Supressor");
        glock.itemInfoName = "Glock";
        glock.ammoInfoName = "Glock";
        glock.modelName = "Glock";
        glock.meshMaterials["GlockBarrel"] = "Glock";
        glock.meshMaterials["GlockMagazine"] = "Glock";
        glock.meshMaterials["GlockMagazine_02"] = "Glock";
        glock.meshMaterials["GlockReceiver"] = "Glock";
        glock.meshMaterials["GlockSlide"] = "Glock";
        glock.meshMaterials["GlockSlideUnLock"] = "Glock";
        glock.meshMaterials["GlockTrigger"] = "Glock";
        glock.meshMaterials["LeupoldRedDot"] = "RedDot";           // Red Dot
        glock.meshMaterials["LeupoldRedDotGlass"] = "RedDotGlass"; // Red Dot
        glock.meshMaterials["Supressor"] = "Suppressor";        // Suppressor
        glock.meshMaterials["ArmsMale"] = "Hands";                 // Arms
        glock.meshMaterials["ArmsFemale"] = "FemaleArms";          // Arms
        glock.animationNames.idle = "Glock_Idle";
        glock.animationNames.walk = "Glock_Walk";
        glock.animationNames.reload = "Glock_Reload";
        glock.animationNames.reloadempty.push_back("Glock_ReloadEmpty");
        glock.animationNames.fire.push_back("Glock_Fire1");
        glock.animationNames.fire.push_back("Glock_Fire2");
        glock.animationNames.fire.push_back("Glock_Fire3");
        glock.animationNames.draw = "Glock_Draw";
        glock.animationNames.drawFirst = "Glock_DrawFirst";
        glock.animationSpeeds.fire = 1.5f;
        glock.animationSpeeds.adsFire = 1.5f;
        glock.muzzleFlashBoneName = "Muzzle";
        glock.casingEjectionBoneName = "EjectionPort";
        glock.pistolSlideBoneName = "Slide";
        glock.pistolSlideOffset = 0.05;
        glock.reloadMagInFrameNumber = 20;
        glock.reloadEmptyMagInFrameNumber = 20;
        glock.audioFiles.fire.push_back("Glock_Fire0.wav");
        glock.audioFiles.fire.push_back("Glock_Fire1.wav");
        glock.audioFiles.fire.push_back("Glock_Fire2.wav");
        glock.audioFiles.fire.push_back("Glock_Fire3.wav");

        //glock.audioFiles.fire.clear();
		//glock.audioFiles.fire.push_back("Glock_FireSuppressed0.wav");
		//glock.audioFiles.fire.push_back("Glock_FireSuppressed1.wav");
		//glock.audioFiles.fire.push_back("Glock_FireSuppressed2.wav");

        glock.audioFiles.reload = "Glock_Reload.wav";
        glock.audioFiles.reloadEmpty = "Glock_ReloadEmpty.wav";
        glock.audioFiles.drawFirst = "Glock_DrawFirst.wav";
        glock.type = WeaponType::PISTOL;
        glock.muzzleFlashOffset = glm::vec3(0, 0.002, 0.005f);
        glock.casingEjectionOffset = glm::vec3(-0.098, -0.033, 0.238);
        glock.animationCancelFrames.draw = 50;
        glock.animationCancelFrames.fire = 2;
        glock.animationCancelFrames.adsFire = 2;
        glock.animationCancelFrames.reload = 40;
        glock.animationCancelFrames.reloadFromEmpty = 40;
        glock.animationCancelFrames.draw = 75.0f;
        glock.animationNames.adsIn = "Glock_ADS_In";
        glock.animationNames.adsOut = "Glock_ADS_Out";
        glock.animationNames.adsIdle = "Glock_ADS_Idle";
        glock.animationNames.adsWalk = "Glock_ADS_Walk";
        glock.animationNames.adsFire.push_back("Glock_ADS_Fire1");
        glock.animationNames.adsFire.push_back("Glock_ADS_Fire2");
        glock.animationNames.adsFire.push_back("Glock_ADS_Fire3");
        glock.damage = 15;
        glock.magSize = 15;
        glock.emptyReloadRequiresSlideOffset = true;
        glock.hasADS = true;
        glock.animationSpeeds.adsIn = 3.0f;
        glock.animationSpeeds.adsOut = 3.0f;
        glock.casingEjectionImpulse = 0.0175f;
        glock.silencerName = "GLOCK_SILENCER";
        glock.sightName = "GLOCK_RED_DOT";

        WeaponInfo& goldeneGlock = CreateWeaponInfo("GoldenGlock");
        goldeneGlock.hiddenMeshAtStart.push_back("ArmsFemale");
        goldeneGlock.itemInfoName = "GoldenGlock";
        goldeneGlock.ammoInfoName = "Glock";
		goldeneGlock.modelName = "Glock";
		goldeneGlock.hiddenMeshAtStart.push_back("LeupoldRedDot");
		goldeneGlock.hiddenMeshAtStart.push_back("LeupoldRedDotGlass");
		goldeneGlock.hiddenMeshAtStart.push_back("Supressor");

        goldeneGlock.meshMaterials["GlockBarrel"] = "GlockGold";
        goldeneGlock.meshMaterials["GlockMagazine"] = "GlockGold";
        goldeneGlock.meshMaterials["GlockMagazine_02"] = "GlockGold";
        goldeneGlock.meshMaterials["GlockReceiver"] = "GlockGold";
        goldeneGlock.meshMaterials["GlockSlide"] = "GlockGold";
        goldeneGlock.meshMaterials["GlockSlideUnLock"] = "GlockGold";
        goldeneGlock.meshMaterials["GlockTrigger"] = "GlockGold";
        goldeneGlock.meshMaterials["LeupoldRedDot"] = "RedDotGold";           // Red Dot
        goldeneGlock.meshMaterials["LeupoldRedDotGlass"] = "RedDotGlass"; // Red Dot
        goldeneGlock.meshMaterials["Supressor"] = "SuppressorGold";        // Suppressor
        goldeneGlock.meshMaterials["ArmsMale"] = "Hands";                 // Arms
        goldeneGlock.meshMaterials["ArmsFemale"] = "FemaleArms";          // Arms
        goldeneGlock.animationNames.idle = "Glock_Idle";
        goldeneGlock.animationNames.walk = "Glock_Walk";
        goldeneGlock.animationNames.reload = "Glock_Reload";
        goldeneGlock.animationNames.reloadempty.push_back("Glock_ReloadEmpty");
        goldeneGlock.animationNames.fire.push_back("Glock_Fire1");
        goldeneGlock.animationNames.fire.push_back("Glock_Fire2");
        goldeneGlock.animationNames.fire.push_back("Glock_Fire3");
        goldeneGlock.animationNames.draw = "Glock_Draw";
        goldeneGlock.animationNames.drawFirst = "Glock_DrawFirst";
        goldeneGlock.animationSpeeds.fire = 1.5f;
        goldeneGlock.animationSpeeds.adsFire = 1.5f;
        goldeneGlock.muzzleFlashBoneName = "Muzzle";
        goldeneGlock.casingEjectionBoneName = "EjectionPort";
        goldeneGlock.pistolSlideBoneName = "Slide";
        goldeneGlock.pistolSlideOffset = 0.05;
        goldeneGlock.reloadMagInFrameNumber = 20;
        goldeneGlock.reloadEmptyMagInFrameNumber = 20;
        goldeneGlock.audioFiles.fire.push_back("Glock_Fire0.wav");
        goldeneGlock.audioFiles.fire.push_back("Glock_Fire1.wav");
        goldeneGlock.audioFiles.fire.push_back("Glock_Fire2.wav");
        goldeneGlock.audioFiles.fire.push_back("Glock_Fire3.wav");
        goldeneGlock.audioFiles.reload = "Glock_Reload.wav";
        goldeneGlock.audioFiles.reloadEmpty = "Glock_ReloadEmpty.wav";
        goldeneGlock.audioFiles.drawFirst = "Glock_DrawFirst.wav";
        goldeneGlock.type = WeaponType::PISTOL;
        goldeneGlock.muzzleFlashOffset = glm::vec3(0, 0.002, 0.005f);
        goldeneGlock.casingEjectionOffset = glm::vec3(-0.098, -0.033, 0.238);
        goldeneGlock.animationCancelFrames.draw = 50;
        goldeneGlock.animationCancelFrames.fire = 2;
        goldeneGlock.animationCancelFrames.adsFire = 2;
        goldeneGlock.animationCancelFrames.reload = 40;
        goldeneGlock.animationCancelFrames.reloadFromEmpty = 40;
        goldeneGlock.animationCancelFrames.draw = 75.0f;
        goldeneGlock.animationNames.adsIn = "Glock_ADS_In";
        goldeneGlock.animationNames.adsOut = "Glock_ADS_Out";
        goldeneGlock.animationNames.adsIdle = "Glock_ADS_Idle";
        goldeneGlock.animationNames.adsWalk = "Glock_ADS_Walk";
        goldeneGlock.animationNames.adsFire.push_back("Glock_ADS_Fire1");
        goldeneGlock.animationNames.adsFire.push_back("Glock_ADS_Fire2");
        goldeneGlock.animationNames.adsFire.push_back("Glock_ADS_Fire3");
        goldeneGlock.damage = 16;
        goldeneGlock.magSize = 80;
        goldeneGlock.emptyReloadRequiresSlideOffset = true;
        goldeneGlock.hasADS = true;
        goldeneGlock.animationSpeeds.adsIn = 3.0f;
        goldeneGlock.animationSpeeds.adsOut = 3.0f;
        goldeneGlock.casingEjectionImpulse = 0.0175f;
        goldeneGlock.silencerName = "GLOCK_SILENCER";
        goldeneGlock.sightName = "GLOCK_RED_DOT";
        goldeneGlock.pistolIsAuto = true;

        //WeaponInfo& glock = CreateWeaponInfo("Glock");
        //glock.itemInfoName = "Glock";
        //glock.modelName = "Glock";
        //glock.meshMaterials["Glock"] = "Glock";
        //glock.meshMaterials["ArmsMale"] = "Hands";
        //glock.meshMaterials["ArmsFemale"] = "FemaleArms";
        //glock.meshMaterials["Glock_silencer"] = "Silencer";
        //glock.meshMaterials["RedDotSight"] = "RedDotSight";
        //glock.meshMaterials["RedDotSightGlass"] = "RedDotSight";
        //glock.hiddenMeshAtStart.push_back("ArmsFemale");
        //glock.hiddenMeshAtStart.push_back("Glock_silencer");
        //glock.animationNames.idle = "Glock_Idle";
        //glock.animationNames.walk = "Glock_Walk";
        //glock.animationNames.reload = "Glock_Reload";
        //glock.animationNames.reloadempty.push_back("Glock_ReloadEmpty");
        //glock.animationNames.fire.push_back("Glock_Fire1");
        //glock.animationNames.fire.push_back("Glock_Fire2");
        //glock.animationNames.fire.push_back("Glock_Fire3");
        //glock.animationNames.draw = "Glock_Draw";
        //glock.animationNames.drawFirst = "Glock_DrawFirst";
        //glock.animationSpeeds.fire = 1.5f;
        //glock.animationSpeeds.adsFire = 1.5f;
        //glock.audioFiles.fire.push_back("Glock_Fire0.wav");
        //glock.audioFiles.fire.push_back("Glock_Fire1.wav");
        //glock.audioFiles.fire.push_back("Glock_Fire2.wav");
        //glock.audioFiles.fire.push_back("Glock_Fire3.wav");
        //glock.audioFiles.reload = "Glock_Reload.wav";
        //glock.audioFiles.reloadEmpty = "Glock_ReloadEmpty.wav";
        //glock.audioFiles.drawFirst = "Glock_DrawFirst.wav";
        //glock.type = WeaponType::PISTOL;
        //glock.muzzleFlashBoneName = "Muzzle";
        //glock.casingEjectionBoneName = "EjectionPort";
        //glock.muzzleFlashOffset = glm::vec3(0, 0.002, 0.005f);
        //glock.casingEjectionOffset = glm::vec3(-0.098, -0.033, 0.238);
        //glock.damage = 15;
        //glock.magSize = 15;
        //glock.ammoInfoName = "Glock";
        //glock.animationCancelFrames.draw = 50.0f;
        //glock.animationCancelFrames.fire = 5;
        //glock.animationCancelFrames.adsFire = 6.0f;
        //glock.animationCancelFrames.reload = 40.0f;
        //glock.animationCancelFrames.reloadFromEmpty = 40.0f;
        //glock.animationCancelFrames.draw = 75.0f;
        //glock.animationNames.adsIn = "Glock_ADS_In";
        //glock.animationNames.adsOut = "Glock_ADS_Out";
        //glock.animationNames.adsIdle = "Glock_ADS_Idle";
        //glock.animationNames.adsWalk = "Glock_ADS_Walk";
        //glock.animationNames.adsFire.push_back("Glock_ADS_Fire1");
        //glock.animationNames.adsFire.push_back("Glock_ADS_Fire2");
        //glock.animationNames.adsFire.push_back("Glock_ADS_Fire3");
        //glock.pistolSlideBoneName = "Slide";
        //glock.pistolSlideOffset = 5;
        //glock.reloadMagInFrameNumber = 20;
        //glock.reloadEmptyMagInFrameNumber = 20;
        //glock.emptyReloadRequiresSlideOffset = true;
        //glock.hasADS = true;
        //glock.animationSpeeds.adsIn = 3.0f;
        //glock.animationSpeeds.adsOut = 3.0f;
        //glock.casingEjectionImpulse = 0.0175f;
        //glock.silencerName = "GLOCK_SILENCER";
        //glock.sightName = "GLOCK_RED_DOT";


        WeaponInfo& knife = CreateWeaponInfo("Knife");
        knife.itemInfoName = "Knife";
        knife.modelName = "Knife";
        knife.type = WeaponType::MELEE;
        knife.damage = 20;
        knife.animationNames.idle = "Knife_Idle";
        knife.animationNames.walk = "Knife_Walk";
        knife.animationNames.draw = "Knife_Draw";
        knife.animationNames.fire.push_back("Knife_Swing0");
        knife.animationNames.fire.push_back("Knife_Swing1");
        knife.animationNames.fire.push_back("Knife_Swing2");
        knife.audioFiles.fire.push_back("Knife.wav");
        knife.meshMaterials["Knife"] = "Knife";
        knife.meshMaterials["ArmsMale"] = "Hands";
        knife.meshMaterials["ArmsFemale"] = "FemaleArms";
        //knife.hiddenMeshAtStart.push_back("ArmsMale");
        knife.hiddenMeshAtStart.push_back("ArmsFemale");

        //WeaponInfo& smith = CreateWeaponInfo("Smith & Wesson");
        //smith.type = WeaponType::PISTOL;
        //smith.damage = 50;
        //smith.modelName = "Smith";
        //smith.animationNames.idle = "Smith_Idle";
        //smith.animationNames.walk = "Smith_Walk";
        //smith.animationNames.revolverReloadBegin = "Smith_ReloadStart";
        //smith.animationNames.revolverReloadLoop = "Smith_ReloadLoop";
        //smith.animationNames.revolverReloadEnd = "Smith_ReloadEnd";
        ////smith.animationNames.reloadempty.push_back("Tokarev_ReloadEmpty");
        //smith.animationNames.fire.push_back("Smith_Fire0");
        //smith.animationNames.fire.push_back("Smith_Fire1");
        //smith.animationNames.fire.push_back("Smith_Fire2");
        //smith.animationSpeeds.fire = 1.0f;
        //smith.animationNames.draw = "Smith_Draw";
        //smith.meshMaterials["ArmsMale"] = "Hands";
        //smith.meshMaterials["ArmsFemale"] = "FemaleArms";
        //smith.meshMaterials["Smith"] = "Smith";
        //smith.meshMaterials["LoadedBullet"] = "SmithBullet";
        //smith.meshMaterials["Bullet_0"] = "SmithBullet";
        //smith.meshMaterials["Bullet_1"] = "SmithBullet";
        //smith.meshMaterials["Bullet_2"] = "SmithBullet";
        //smith.meshMaterials["Bullet_3"] = "SmithBullet";
        //smith.meshMaterials["Bullet_4"] = "SmithBullet";
        //smith.meshMaterials["Bullet_5"] = "SmithBullet";
        //smith.hiddenMeshAtStart.push_back("ArmsFemale");
        //smith.audioFiles.fire.push_back("Smith_Fire0.wav");
        //smith.audioFiles.fire.push_back("Smith_Fire1.wav");
        //smith.audioFiles.fire.push_back("Smith_Fire2.wav");
        //smith.audioFiles.revolverCocks.push_back("Smith_Cock0.wav");
        //smith.audioFiles.revolverCocks.push_back("Smith_Cock1.wav");
        //smith.audioFiles.revolverCocks.push_back("Smith_Cock2.wav");
        //smith.muzzleFlashBoneName = "muzzle";
        //smith.type = WeaponType::PISTOL;
        //smith.damage = 500;
        //smith.magSize = 6;
        //smith.casingEjectionBoneName = "Ejection";
        //smith.casingEjectionOffset = glm::vec3(-0.066, -0.007, 0.249);
        //smith.ammoType = "Tokarev";
        //smith.animationCancelFrames.draw = 50.0f;
        //smith.animationCancelFrames.fire = 5.0f;
        //smith.animationCancelFrames.reload = 80.0f;
        //smith.animationCancelFrames.reloadFromEmpty = 80.0f;
        //smith.revolverCockFrameNumber = 18;
        //smith.relolverStyleReload = true;
        //smith.casingEjectionImpulse = 0.0175f;

        WeaponInfo& tokarev = CreateWeaponInfo("Tokarev");
        tokarev.itemInfoName = "Tokarev";
        tokarev.modelName = "Tokarev";
        tokarev.meshMaterials["ArmsMale"] = "Hands";
        tokarev.meshMaterials["ArmsFemale"] = "FemaleArms";
        tokarev.meshMaterials["TokarevBody"] = "Tokarev";
        tokarev.meshMaterials["Tokarev_Barrel"] = "Tokarev";
        tokarev.meshMaterials["Tokarev_Hammer"] = "Tokarev";
        tokarev.meshMaterials["Tokarev_Slide"] = "Tokarev";
        tokarev.meshMaterials["Tokarev_SlideCatch"] = "Tokarev";
        tokarev.meshMaterials["TokarevBody_Trigger"] = "Tokarev";
        tokarev.meshMaterials["TokarevBody"] = "Tokarev";
        tokarev.meshMaterials["TokarevMag_01"] = "TokarevMag";
        tokarev.meshMaterials["TokarevMag_02"] = "TokarevMag";
        tokarev.meshMaterials["TokarevGripPolymer"] = "TokarevGrip";
        tokarev.meshMaterials["TokarevGripWood"] = "TokarevGrip";

        tokarev.hiddenMeshAtStart.push_back("ArmsFemale");
        tokarev.hiddenMeshAtStart.push_back("TokarevGripWood");
        tokarev.animationNames.fire.push_back("Tokarev_Fire1");
        tokarev.animationNames.fire.push_back("Tokarev_Fire2");
        tokarev.animationNames.fire.push_back("Tokarev_Fire3");
        tokarev.animationNames.idle = "Tokarev_Idle";
        tokarev.animationNames.draw = "Tokarev_Draw";
        tokarev.animationNames.drawFirst = "Tokarev_DrawFirst";
        tokarev.animationNames.walk = "Tokarev_Walk";
        tokarev.animationNames.fire.push_back("Tokarev_Fire1");
        tokarev.animationNames.fire.push_back("Tokarev_Fire2");
        tokarev.animationNames.fire.push_back("Tokarev_Fire3");
        tokarev.animationNames.reload = "Tokarev_Reload";
        tokarev.animationNames.reloadempty.push_back("Tokarev_ReloadEmpty");
        tokarev.animationSpeeds.fire = 1.5f;
        tokarev.audioFiles.fire.push_back("Tokarev_Fire0.wav");
        tokarev.audioFiles.fire.push_back("Tokarev_Fire1.wav");
        tokarev.audioFiles.fire.push_back("Tokarev_Fire2.wav");
        tokarev.audioFiles.fire.push_back("Tokarev_Fire3.wav");
        tokarev.audioFiles.reload = "Tokarev_Reload.wav";
        tokarev.audioFiles.reloadEmpty = "Tokarev_ReloadEmpty.wav";
        tokarev.audioFiles.drawFirst = "Tokarev_DrawFirst.wav";
        tokarev.type = WeaponType::PISTOL;
        tokarev.muzzleFlashBoneName = "Muzzle";
        tokarev.casingEjectionBoneName = "Ejection";
        tokarev.muzzleFlashOffset = glm::vec3(0, 0.002, 0.005f);
        tokarev.casingEjectionOffset = glm::vec3(-0.098, -0.033, 0.238);
        tokarev.damage = 35;
        tokarev.magSize = 15;
        tokarev.ammoInfoName = "Tokarev";
        tokarev.animationCancelFrames.draw = 50.0f;
        tokarev.animationCancelFrames.fire = 5;
        tokarev.animationCancelFrames.adsFire = 6.0f;
        tokarev.animationCancelFrames.reload = 40.0f;
        tokarev.animationCancelFrames.reloadFromEmpty = 40.0f;
        tokarev.animationCancelFrames.draw = 75.0f;
        tokarev.pistolSlideBoneName = "Slide";
        tokarev.pistolSlideOffset = 5;
        tokarev.reloadMagInFrameNumber = 20;
        tokarev.reloadEmptyMagInFrameNumber = 20;
        tokarev.emptyReloadRequiresSlideOffset = true;
        tokarev.hasADS = false;
        tokarev.casingEjectionImpulse = 0.0175f;




        WeaponInfo& spas = CreateWeaponInfo("SPAS");
        spas.itemInfoName = "SPAS";
        spas.modelName = "SPAS";
        spas.meshMaterials["ArmsMale"] = "Hands";
        spas.meshMaterials["ArmsFemale"] = "FemaleArms";
        spas.meshMaterials["Shells"] = "Shell";
        spas.meshMaterials["Shells.001"] = "Shell";
        spas.meshMaterials["SPAS12_Main"] = "SPAS2_Main";
        spas.meshMaterials["SPAS12_Moving"] = "SPAS2_Moving";
        spas.meshMaterials["SPAS12_Stamped"] = "SPAS2_Stamped";
        spas.animationSpeeds.fire = 1.0f;
        spas.animationSpeeds.shotgunReloadStart = 1.0f;
        spas.animationSpeeds.shotgunReloadEnd = 1.0f;
        spas.animationSpeeds.shotgunReloadOneShell = 1.25f;
        spas.animationSpeeds.shotgunReloadTwoShells = 1.25f;
        spas.animationNames.idle = "SPAS_Idle";
        spas.animationNames.walk = "SPAS_Walk";
        spas.animationNames.melee = "SPAS_Melee";
        spas.animationNames.reload = "SPAS_Fire";
        spas.animationNames.reloadempty.push_back("SPAS_Fire");
        spas.animationNames.fire.push_back("SPAS_Fire");
        spas.animationNames.draw = "SPAS_Draw";
        spas.animationNames.shotgunReloadStart = "SPAS_ReloadStart";
        spas.animationNames.shotgunReloadEnd = "SPAS_ReloadEnd";
        spas.animationNames.shotgunDrawPump = "SPAS_DrawPump";
        spas.animationNames.shotgunFireNoPump = "SPAS_FireNoPump";
        spas.animationNames.shotgunReloadEndPump = "SPAS_ReloadEndPump";
        spas.animationNames.shotgunReloadOneShell = "SPAS_Reload1Shell";
        spas.animationNames.shotgunReloadTwoShells = "SPAS_Reload2Shells";
        spas.animationNames.shotgunUnloadStart = "SPAS_UnloadStart";
        spas.animationNames.shotgunUnloadOneShell = "SPAS_UnloadOneShell";
        spas.animationNames.shotgunUnloadTwoShells = "SPAS_UnloadTwoShells";
        spas.animationNames.shotgunUnloadEnd = "SPAS_UnloadEnd";
        spas.audioFiles.fire.push_back("SPAS_Fire.wav");
        spas.audioFiles.shotgunPump = "SPAS_Pump.wav";
        spas.type = WeaponType::SHOTGUN;
        spas.muzzleFlashOffset = glm::vec3(0, 0.002, 0.005f);
        spas.casingEjectionOffset = glm::vec3(-0.098, -0.033, 0.238);
        spas.damage = 15;
        spas.magSize = 8;
        spas.ammoInfoName = "12GaugeBuckShot";
        spas.hiddenMeshAtStart.push_back("ArmsFemale");
        spas.muzzleFlashBoneName = "Muzzle";
        spas.casingEjectionBoneName = "Shell_bone";
        spas.casingEjectionImpulse = 0.0175f;
        spas.animationCancelFrames.fire = 50.0f;
        spas.animationNames.dryFire = "SPAS_DryFire";
        spas.animationNames.toggleAutoShotgun = "SPAS_ToggleAuto";
        spas.hasAutoSwitch = true;
        spas.animationSpeeds.melee = 1.25f;

        WeaponInfo& remington870 = CreateWeaponInfo("Remington870");
        remington870.itemInfoName = "Remington870";
        remington870.modelName = "Remington870";
        remington870.meshMaterials["Shotgun"] = "Shotgun";
        remington870.meshMaterials["ArmsMale"] = "Hands";
        remington870.meshMaterials["ArmsFemale"] = "FemaleArms";
        remington870.animationNames.shotgunReloadStart = "Remington870_ReloadStart";
        remington870.animationNames.shotgunReloadEnd = "Remington870_ReloadEnd";
        remington870.animationNames.shotgunDrawPump = "Remington870_DrawPump";
        remington870.animationNames.shotgunReloadOneShell = "Remington870_Reload1Shell";
        remington870.animationNames.shotgunReloadTwoShells = "Remington870_Reload2Shells";
        remington870.animationNames.idle = "Remington870_Idle";
        remington870.animationNames.walk = "Remington870_Walk";
        remington870.animationNames.melee = "Remington870_Melee";
        remington870.animationNames.reload = "Remington870_Fire";
        remington870.animationNames.reloadempty.push_back("Remington870_Fire");
        remington870.animationNames.fire.push_back("Remington870_Fire");
        remington870.animationNames.draw = "Remington870_Draw";
        remington870.animationNames.shotgunDrawPump = "Remington870_DrawPump";
        remington870.animationNames.shotgunReloadStart = "Remington870_ReloadStart";
        remington870.animationNames.shotgunReloadEnd = "Remington870_ReloadEnd";
        remington870.animationNames.shotgunReloadEndPump = "Remington870_ReloadEndPump";
        remington870.animationNames.shotgunReloadOneShell = "Remington870_Reload1Shell";
        remington870.animationNames.shotgunReloadTwoShells = "Remington870_Reload2Shells";
        remington870.animationNames.shotgunFireNoPump = "Remington870_FireNoPump";
        remington870.animationSpeeds.melee = 1.25f;
        remington870.audioFiles.fire.push_back("Shotgun_Fire.wav");
        remington870.audioFiles.shotgunPump = "SPAS_Pump.wav";
        remington870.type = WeaponType::SHOTGUN;
        remington870.muzzleFlashOffset = glm::vec3(0, 0.002, 0.005f);
        remington870.casingEjectionOffset = glm::vec3(-0.098, -0.033, 0.238);
        remington870.damage = 14;
        remington870.magSize = 8;
        remington870.ammoInfoName = "12GaugeBuckShot";
        remington870.hiddenMeshAtStart.push_back("ArmsFemale");
        remington870.muzzleFlashBoneName = "Muzzle";
        remington870.casingEjectionBoneName = "Shell_bone";
        remington870.casingEjectionImpulse = 0.0175f;
        remington870.animationCancelFrames.fire = 50.0f;
        remington870.animationNames.dryFire = "SPAS_DryFire";
        remington870.animationNames.toggleAutoShotgun = "SPAS_ToggleAuto";
        remington870.hasAutoSwitch = false;

        WeaponInfo& p90 = CreateWeaponInfo("P90");
        p90.modelName = "P90";
        p90.itemInfoName = "P90";
        p90.type = WeaponType::AUTOMATIC;
        p90.damage = 20;
        p90.hasADS = true;
        p90.animationNames.idle = "P90_Idle";
        p90.animationNames.walk = "P90_Walk";
        p90.animationNames.draw = "P90_Draw";
        p90.animationNames.reload = "P90_Reload";
        p90.animationNames.reloadempty.push_back("P90_ReloadEmpty");
        p90.animationNames.fire.push_back("P90_Fire0");
        p90.animationNames.fire.push_back("P90_Fire1");
        p90.animationNames.fire.push_back("P90_Fire2");
        p90.hiddenMeshAtStart.push_back("ArmsFemale");
        p90.meshMaterials["ArmsMale"] = "Hands";
        p90.meshMaterials["ArmsFemale"] = "FemaleArms";

        p90.meshMaterials["Magazine_low"] = "P90_Mag";
        p90.meshMaterials["Magazine_low2"] = "P90_Mag";
        p90.meshMaterials["LowerReceiver_low"] = "P90_Main";
        p90.meshMaterials["Object_0.002"] = "P90_Rails"; // SideRail_low
        p90.meshMaterials["TopRailStandard_low"] = "P90_Rails";
        p90.meshMaterials["UpperReceiver_low"] = "P90_FrontEnd";
        p90.meshMaterials["SideRailScrews_low"] = "P90_Rails";
        p90.meshMaterials["Compensator_low"] = "P90_FrontEnd";
        p90.meshMaterials["ChargingHandle_low"] = "P90_FrontEnd"; //  ChargingHandle_low OR Sheet_806.001
        p90.meshMaterials["Solid_805.001"] = "P90_FrontEnd"; // ChargingHamdlePlate_low
        p90.meshMaterials["Trigger_low"] = "P90_Main";
		p90.meshMaterials["FireSelector_low"] = "P90_Main";
		p90.meshMaterials["MagRelease_low"] = "P90_Main";
		p90.meshMaterials["Solid_547.003"] = "P90_Mag"; // Follower_low
		p90.meshMaterials["P90Magazine.001"] = "P90_Mag"; // spring!!! aka MagazineSpring_low
		p90.meshMaterials["Revolved.020"] = "P90_Mag"; // MagazineRollers_low
		p90.meshMaterials["Revolved.021"] = "P90_Mag"; // MagazineRollers_low.001
		p90.meshMaterials["Barrel_low"] = "P90_FrontEnd"; // MagazineRollers_low.001
		p90.meshMaterials["BoltBars_low"] = "P90_Main";
		p90.meshMaterials["Bolt_low"] = "P90_Main";
		p90.meshMaterials["TopRailScrews_low"] = "P90_FrontEnd";
        p90.meshMaterials["Velcro_Clip"] = "P90_Sling";
        p90.meshMaterials["Revolved.001"] = "P90_Mag";
        p90.meshMaterials["Revolved.002"] = "P90_Mag";
        p90.meshMaterials["Revolved.003"] = "P90_Mag";
        p90.meshMaterials["Revolved.004"] = "P90_Mag";
        p90.meshMaterials["Revolved.005"] = "P90_Mag";
        p90.meshMaterials["Revolved.006"] = "P90_Mag";
        p90.meshMaterials["Revolved.007"] = "P90_Mag";
        p90.meshMaterials["Revolved.008"] = "P90_Mag";
        p90.meshMaterials["Revolved.009"] = "P90_Mag";
        p90.meshMaterials["Revolved.010"] = "P90_Mag";
        p90.meshMaterials["Revolved.011"] = "P90_Mag";
        p90.meshMaterials["Revolved.012"] = "P90_Mag";
        p90.meshMaterials["Revolved.013"] = "P90_Mag";
        p90.meshMaterials["Revolved.014"] = "P90_Mag";
        p90.meshMaterials["Revolved.015"] = "P90_Mag";
        p90.meshMaterials["Revolved.016"] = "P90_Mag";
        p90.meshMaterials["Revolved.017"] = "P90_Mag";
        p90.meshMaterials["Revolved.018"] = "P90_Mag";
        p90.meshMaterials["Revolved.019"] = "P90_Mag";
        p90.meshMaterials["Revolved.022"] = "P90_Mag";
        p90.meshMaterials["Revolved.023"] = "P90_Mag";
        p90.meshMaterials["Revolved.024"] = "P90_Mag";
        p90.meshMaterials["Revolved.025"] = "P90_Mag";
        p90.meshMaterials["Revolved.026"] = "P90_Mag";
        p90.meshMaterials["Revolved.027"] = "P90_Mag";
        p90.meshMaterials["Revolved.028"] = "P90_Mag";
        p90.meshMaterials["Revolved.029"] = "P90_Mag";
        p90.meshMaterials["Revolved.030"] = "P90_Mag";
        p90.meshMaterials["Revolved.031"] = "P90_Mag";
        p90.meshMaterials["Revolved.032"] = "P90_Mag";
        p90.meshMaterials["Revolved.033"] = "P90_Mag";
        p90.meshMaterials["Revolved.034"] = "P90_Mag";
        p90.meshMaterials["Revolved.035"] = "P90_Mag";
        p90.meshMaterials["Revolved.036"] = "P90_Mag";
        p90.meshMaterials["Revolved.037"] = "P90_Mag";
        p90.meshMaterials["Revolved.038"] = "P90_Mag";
        p90.meshMaterials["Revolved.039"] = "P90_Mag";
        p90.meshMaterials["Revolved.040"] = "P90_Mag";
        p90.meshMaterials["Revolved.041"] = "P90_Mag";
        p90.meshMaterials["Revolved.042"] = "P90_Mag";
        p90.meshMaterials["Revolved.043"] = "P90_Mag";
        p90.meshMaterials["Revolved.044"] = "P90_Mag";
        p90.meshMaterials["Revolved.045"] = "P90_Mag";
        p90.meshMaterials["Revolved.046"] = "P90_Mag";
        p90.meshMaterials["Revolved.047"] = "P90_Mag";
        p90.meshMaterials["Revolved.048"] = "P90_Mag";
        p90.meshMaterials["Revolved.049"] = "P90_Mag";
        p90.meshMaterials["Revolved.050"] = "P90_Mag";
        p90.meshMaterials["Revolved.051"] = "P90_Mag";
        p90.meshMaterials["Revolved.052"] = "P90_Mag";
        p90.meshMaterials["Revolved.053"] = "P90_Mag";

        p90.ammoInfoName = "P90";
        p90.magSize = 50;

        p90.casingEjectionBoneName = "SlideCatch";
        p90.casingEjectionOffset = glm::vec3(0, 0, 0);
        p90.animationCancelFrames.fire = 15.0f;
        p90.animationCancelFrames.reload = 95.0f;
        p90.animationCancelFrames.reloadFromEmpty = 95.0f;
        p90.animationCancelFrames.draw = 75.0f;
        p90.animationCancelFrames.adsFire = 10.0;
        p90.audioFiles.fire.push_back("P90_Fire0.wav");
        p90.audioFiles.fire.push_back("P90_Fire1.wav");
        p90.audioFiles.fire.push_back("P90_Fire2.wav");
        p90.audioFiles.fire.push_back("P90_Fire3.wav");
        p90.audioFiles.reload = "P90_Reload.wav";
        p90.audioFiles.reloadEmpty = "P90_ReloadEmpty.wav";
        p90.casingEjectionBoneName = "Ejection_Port";  // FIGURE THIS OUT LATER
        p90.casingEjectionBoneName = "Weapon";
        p90.muzzleFlashScale = 1.5f;
        p90.casingEjectionImpulse = 0.0175f;
        p90.reloadMagInFrameNumber = 23;
        p90.reloadEmptyMagInFrameNumber = 21;
        p90.animationNames.adsIn = "P90_ADS_In";
        p90.animationNames.adsOut = "P90_ADS_Out";
        p90.animationNames.adsIdle = "P90_ADS_Idle";
        p90.animationNames.adsWalk = "P90_ADS_Idle";
        p90.animationNames.adsFire.push_back("P90_ADS_Fire0");
        p90.animationNames.adsFire.push_back("P90_ADS_Fire1");
        p90.animationNames.adsFire.push_back("P90_ADS_Fire2");

		p90.animationCancelFrames.fire = 3.0f;
		p90.animationCancelFrames.reload = 80.0f;
		p90.animationCancelFrames.reloadFromEmpty = 95.0f;
		p90.animationCancelFrames.draw = 75.0f;
		p90.animationCancelFrames.adsFire = 3.0f;
		p90.animationSpeeds.fire = 2.5f;
		p90.animationSpeeds.reload = 1.125f;
		p90.animationSpeeds.reloadempty = 1.125f;
		p90.animationSpeeds.adsFire = 2.5f;
		p90.animationSpeeds.draw = 1.225f;
		p90.animationSpeeds.adsIn = 3.0f;
		p90.animationSpeeds.adsOut = 3.0f;

		p90.muzzleFlashBoneName = "Muzzle";
		p90.muzzleFlashOffset = glm::vec3(0, 0.002, 40.9207f);
    }


    int32_t GetWeaponMagSize(const std::string& name) {
        if (WeaponInfo* weaponInfo = GetWeaponInfoByName(name)) {
            return weaponInfo->magSize;
        }
        return 0;
    }
}